### ISSUE TITLE
GPU drops to powersave/desktop clocks on Boss week

### ISSUE THREAD

**Issue by Deshke** [megai2/d912pxy#136] opened 2019-05-09 20:14 UTC
**Describe the bug**

while in Boss week the GPU (2080 ti) drops down to desktop clock speeds while still maintaining 50% core load causing shutter, while the game stays at around 20-25 FPS 

**To Reproduce**

1. take part in the boss week // or other large player assemblies with high drawcall 
2. see screen 1 for settings
3. watch the frame drops while some boss gets slayin
4. look up stats in hwinfo64

**Expected behavior**

gpu does not drop to desktop speeds / stays in game mode

**Screenshots**

settings: 
![image](https://user-images.githubusercontent.com/1473225/57482857-ffe6d900-72a5-11e9-8d7e-23fd5900baab.png)

temps/usage 
![image](https://user-images.githubusercontent.com/1473225/57482834-efcef980-72a5-11e9-89fd-5ccacd8920fd.png)

reference screen 
![image](https://user-images.githubusercontent.com/1473225/57483126-84d1f280-72a6-11e9-9222-9ae7904aa40e.png)
![image](https://user-images.githubusercontent.com/1473225/57483225-a59a4800-72a6-11e9-827d-e7a669bc87f5.png)

![image](https://user-images.githubusercontent.com/1473225/57483405-12154700-72a7-11e9-8f54-dcdab428b128.png)

**Standard information**

1. Windows 10 18362
2. Hardware info:  see last reference screen from capframeX
3. nvidia r430
4. https://github.com/megai2/d912pxy/releases/tag/v0.9.9.1b

**Comment by Deshke** [comment] 2019-05-09 20:26
![performance_graph](https://user-images.githubusercontent.com/1473225/57484471-66212b00-72a9-11e9-9312-ea69e16dd1ca.png)

[20190509-22192700.zip](https://github.com/megai2/d912pxy/files/3163870/20190509-22192700.zip)

**Comment by Deshke** [comment] 2019-05-09 20:36
somehow this occurs only if there are a lot of objects on screen, as if there where a limit for the called objects -> some overflow -> gpu drops down to desktop speeds, if there a less objects the gpu jumps back to "normal" speeds/framerates

**Comment by megai2** [comment] 2019-05-09 20:40
looks like gpu decides that there is not enough load to work in game mode

**Comment by Deshke** [comment] 2019-05-09 20:43
which is strange on it's own

**Comment by megai2** [comment] 2019-05-09 20:47
> 
> 
> which is strange on it's own

i think there is somekind of software tracking on driver side to keep clocks at max, but not for dx12

**Comment by megai2** [comment] 2019-05-09 21:07
is vsync on?

**Comment by Deshke** [comment] 2019-05-09 21:11
reshade from your discord build/link   - gsync only

**Comment by Deshke** [comment] 2019-05-09 21:12
did test it with native gw2 and reshade, framerate is terrible but the gpu does not go to powersave mode

**Comment by megai2** [comment] 2019-05-09 21:24
can you run it with force vsync/gsync off?

**Comment by megai2** [comment] 2019-05-09 21:36
and also, what about workarounds such as force highpower mode or any "recognizable" software in background?

**Comment by a5744585** [comment] 2019-05-10 04:38
NV past this will happen.
You should wait for a new driver or lower the driver version.
W10 version number 1809 is also possible.

**Comment by megai2** [comment] 2019-05-10 05:12
Another problem can be in 8k draws per frame limit, but i'm not see this in logs, should be 
```4BBDC5 [ error ] iframe | batches in one frame exceeded PXY_INNER_MAX_IFRAME_BATCH_COUNT, performing queued commands now ``` 

if it reaches that

**Comment by Deshke** [comment] 2019-05-10 06:24
> can you run it with force vsync/gsync off?

gsync off changes nothing so far 

> and also, what about workarounds such as force highpower mode or any "recognizable" software in background?

did try with the gpu-z render test in the background, gpu jumps to the 2 Ghz boost clock but gw2 was unaffected, as soon as i stopped the render test the gpu did go back to "sleep" 

next try is the nv 430.64 driver.

**Comment by Deshke** [comment] 2019-05-10 16:55
manually forcing "high energy/performance mode" within the nvidia driver for gw2 forces the card to stay on the minimum "game" clock

![image](https://user-images.githubusercontent.com/1473225/57543561-fcf6f180-7354-11e9-8359-c97f74e9608d.png)

**Comment by megai2** [comment] 2019-05-10 17:13
Then it should be normal, anyway i not found any GPU wait times in metric logs.
Issue can be on that 8k draw calls limit or on CPU lag

**Comment by Deshke** [comment] 2019-05-10 17:21
as these only occur while a lot of players get together i assume the 8k limit is reached and at  4Ghz on 12 cores some bottleneck is reached. if i set the char quality to lowest it gets better.

**Comment by Deshke** [comment] 2019-05-10 17:24
![image](https://user-images.githubusercontent.com/1473225/57544968-34679d00-7359-11e9-9c33-df88816db07f.png)

**Comment by megai2** [comment] 2019-05-10 17:29
> 
> 
> as these only occur while a lot of players get together i assume the 8k limit is reached and at 4Ghz on 12 cores some bottleneck is reached. if i set the char quality to lowest it gets better.

when 8k limit is reached log will be full of that error messages

**Comment by Deshke** [comment] 2019-05-10 17:31
is there a way to log the number of dawcalls per frame?

**Comment by megai2** [comment] 2019-05-10 17:44
> 
> 
> is there a way to log the number of dawcalls per frame?

performance_graph.png shows frametime(FPS) vs draw calls per frame

**Comment by Deshke** [comment] 2019-05-10 17:51
but not on a high resolution scale, so i currently suspect that there are like 5-7.5k calls are being made(or more) and that.

or some obscure CPU bottleneck

**Comment by megai2** [comment] 2019-05-10 19:26
> 
> 
> but not on a high resolution scale, so i currently suspect that there are like 5-7.5k calls are being made(or more) and that.
> 
> or some obscure CPU bottleneck

1024x1024 image, ~8draw calls per pixel sooo it shows almost 5k draw calls max occured (on one that you attached).

you can always switch defines in perf graph code to make it anything you like

**Comment by megai2** [comment] 2019-05-10 19:32
one thing i also note about OCAT it shows spikes on some frames that are not recorded in metric logs
i suspect OCAT ignores or your system somehow waits on frames that should be skipped/presented partly (dxgi in windowed mode allows only that behaivor)

can you see what will happen in fullscreen?

**Comment by Deshke** [comment] 2019-05-10 20:08
![image](https://user-images.githubusercontent.com/1473225/57552966-ce394500-736d-11e9-9968-17fae2530887.png)

![image](https://user-images.githubusercontent.com/1473225/57553091-10628680-736e-11e9-830d-930ac9ef456a.png)


fullscreen with the high performance mode enabled for gw2 in the nvidia settings (gpu core at 1350Mhz the whole time)


with "normal" driver performance setting and fullscreen the gpu drops again down to desktop / non game mode 

![image](https://user-images.githubusercontent.com/1473225/57553829-06418780-7370-11e9-96b9-e8c1721cdf38.png)


diff between the two

![image](https://user-images.githubusercontent.com/1473225/57553858-19ecee00-7370-11e9-8a5d-a594c2e5942d.png)

**Comment by megai2** [comment] 2019-05-10 21:15
and ofc it keep work fine on dx9?

**Comment by Deshke** [comment] 2019-05-10 21:16
framerate is shitty but the gpu does not go into desktop mode

**Comment by moriz1** [comment] 2019-05-12 15:30
I can replicate this behaviour with my 2080ti and dx9 as well: run the game with graphics setting on "best performance. Or, turn on subsampling.

On the video card end, this seems to be exclusively caused by low GPU load. As soon as GPU load drops below 40%, it will start throttling. It just so happens that d912pxy generally cause lower GPU load for some reason, so the problem becomes a lot more noticeable.

**Comment by megai2** [comment] 2019-05-13 06:59
will try to take some code from https://1vwjbxf1wko0yhnr.wordpress.com/2015/08/10/overclocking-tools-for-nvidia-gpus-suck-i-made-my-own/ to force set correct pstate

**Comment by moriz1** [comment] 2019-05-14 18:45
Might be a good idea to have this be a config file option. Correct me if I'm wrong, but this method of setting clock speeds isn't universal across all video cards.

**Comment by WanYaa** [comment] 2019-05-19 16:11
you might give msi afterburner a try
https://www.guru3d.com/files-details/msi-afterburner-beta-download.html

**Comment by megai2** [comment] 2019-05-27 19:24
https://en-forum.guildwars2.com/discussion/comment/929040 can someone repeat that problem with plain dx9?

**Comment by Deshke** [comment] 2019-05-27 19:41
i currently can not replicate the issue, because it only happend to me within the boss week.

Even with wvw blob fights on EBG i do not run into the issue currently

**Comment by megai2** [comment] 2019-05-27 21:04
that man getting it by setting all low on dx9

**Comment by ParanoidHitman** [comment] 2019-06-06 21:25
Man GPU usage is not properly optimazed. I have the exact same problem as that guy on my AMD RX 580, i need to use supersampling in order for the gpu usage pass 50% so it max the clock speed.
Please fix this issue! Thank you very much for all the stuff you do for us players, but please fix the usage problem of the gpu

**Comment by Deshke** [comment] 2019-07-20 06:52
new boss week and it got better

![image](https://user-images.githubusercontent.com/1473225/61575377-52751a80-aacb-11e9-967b-6b00562e613e.png)


blue line is ppl waiting, green is in fight. Strangely enough if there are less than 50(ish) players on screen or not much effects happening, the gpu goes to 1800~2000Mhz, but as soon as there are many effects happening it goes down to 1350 base game clock

**Comment by megai2** [comment] 2019-09-25 19:24
Tested this new config option, works fine for me, Alrai and more ppl on discord.

I keep issue opened for more time if there is something wrong.

**Comment by megai2** [comment] 2019-10-02 11:15
Looks like all fine. Closing for now.

**Closed by megai2** 2019-10-02 11:15 UTC
Labels: bug
