### ISSUE TITLE
Crash after last update?

### ISSUE THREAD

**Issue by gele05** [megai2/d912pxy#358] opened 2021-04-06 16:22 UTC
If i remove arcdps and keep D912PXY after the last update, the game crash. The problem is related to the game?

**Comment by rburketaylor** [comment] 2021-04-06 16:28
Yeah, I'm thinking the April 6th update borked it cause it was working last night.

**Comment by LinearBotSystems** [comment] 2021-04-06 16:29
It doesn't crash for me but it looks like a wild drug trip also I'm on a older version because the new version look up freeze on full screen for me. Which by the way does it now too. ArcDPS on its own crahs too.

I'm not sure what Arena.NET is doing in the background a couple of weeks ago I noticed the game again got lower FPS, also they changed the EULA.

**Comment by the-nic** [comment] 2021-04-06 16:29
here is a stacktrace
```
Apr 06 18:28:00 client: --- trace ---
			ep 0x7FFEBC1A4F2A frame 0x00D1903FC090 rva 0x000000044F2A in d3d9_chainload @ d912pxy_hlsl_generator::Process
			ep 0x7FFEBC1B3C38 frame 0x00D1903FE0F0 rva 0x000000053C38 in d3d9_chainload @ d912pxy_shader_replacer::GenerateHLSL
			ep 0x7FFEBC1B3DE5 frame 0x00D1903FE950 rva 0x000000053DE5 in d3d9_chainload @ d912pxy_shader_replacer::GetHLSL
			ep 0x7FFEBC1AD55D frame 0x00D1903FFA00 rva 0x00000004D55D in d3d9_chainload @ d912pxy_pso_item::PerformRCE
			ep 0x7FFEBC1AE0F8 frame 0x00D1903FFA50 rva 0x00000004E0F8 in d3d9_chainload @ d912pxy_pso_item::RealtimeIntegrityCheck
			ep 0x7FFEBC1AC794 frame 0x00D1903FFB90 rva 0x00000004C794 in d3d9_chainload @ d912pxy_pso_item::Compile
			ep 0x7FFEBC1AAEAC frame 0x00D1903FFBC0 rva 0x00000004AEAC in d3d9_chainload @ d912pxy_pso_db::ThreadJob
			ep 0x7FFEBC1BB3D8 frame 0x00D1903FFBF0 rva 0x00000005B3D8 in d3d9_chainload @ d912pxy_thread_main
			ep 0x7FFF02637034 frame 0x00D1903FFC20 rva 0x000000017034 in KERNEL32
			ep 0x7FFF032E2651 frame 0x00D1903FFCA0 rva 0x000000052651 in ntdll
			thread start 0x7FFEBC1BB380 rva 0x00000005B380 in d3d9_chainload @ d912pxy_thread_main
```

**Comment by demonpuppet** [comment] 2021-04-06 16:32
Anet DONE DID IT AGAIN BOIS

**Comment by Jong1** [comment] 2021-04-06 16:34
Also, don't seem to be able to uninstall. "Remove" appears to work but d912pxy still loads afterwards. if the folder is deleted GW2 does not load at all saying it cannot save the config to the dx912pxy folder.

**Comment by Zyian** [comment] 2021-04-06 16:36
> 
> 
> Also, don't seem to be able to uninstall. "Remove" appears to work but d912pxy still loads afterwards. if the folder is deleted GW2 does not load at all saying it cannot save the config to the dx912pxy folder.
> Running uninstall again says that it believes it is already uninstalled!

Go to the GW2 folder and rename the `addons` folder temporarily like `_addons` the game loaded for me after

**Comment by demonpuppet** [comment] 2021-04-06 16:37
> > Also, don't seem to be able to uninstall. "Remove" appears to work but d912pxy still loads afterwards. if the folder is deleted GW2 does not load at all saying it cannot save the config to the dx912pxy folder.
> > Running uninstall again says that it believes it is already uninstalled!
> 
> Go to the GW2 folder and rename the `addons` folder temporarily like `_addons` the game loaded for me after

Is this fixing it? Or is this just to successfully uninstall?

**Comment by Jong1** [comment] 2021-04-06 16:37
I manually deleted the dll in Bin64 and that fixed it :).

**Comment by rburketaylor** [comment] 2021-04-06 16:38
Also doing a "clean" install on gw2 addon manager works if you use that.

**Comment by victorsouzaleal** [comment] 2021-04-06 16:51
just rename d912pxy folder to .d912pxy inside addons in game path

**Comment by Jong1** [comment] 2021-04-06 16:56
That does not work for me. The addons folder was deleted when I "removed", but the dll was left for some reason.

**Comment by demonpuppet** [comment] 2021-04-06 17:29
> just rename d912pxy to .d912pxy inside addons folder in game path. And wait for update

What does this do?

**Comment by rodcampos21** [comment] 2021-04-06 17:30
Not working for me too.

**Comment by arianebrandao** [comment] 2021-04-06 17:41
> If i remove arcdps and keep D912PXY after the last update, the game crash. The problem is related to the game?

Same here

**Comment by Ghostkat9** [comment] 2021-04-06 17:45
> > just rename d912pxy to .d912pxy inside addons folder in game path. And wait for update
> 
> What does this do?

Not sure, I think it disables the folder from being read, but it worked for me to just rename the folder with a . in front like victorsouzaleal said.

**Comment by Leguron** [comment] 2021-04-06 17:46
Please update it to make it work again. I have very low FPS without it.

**Comment by LuniaDev** [comment] 2021-04-06 18:12
Yep, game doesn't work at all for me right now either. Crashes after 1-2 seconds on the character screen with d912pxy. Tried a fresh reinstall of the game + d912pxy, same thing. Game works fine until you install d912pxy.

**Comment by doryxbirb** [comment] 2021-04-06 18:34
d912pxy/log.txt without arcDPS or any other addon
[log.txt](https://github.com/megai2/d912pxy/files/6266842/log.txt)

last version of arcDPS alone works without problems despite what others reported

**Comment by STEFOULIS** [comment] 2021-04-06 18:39
the same probllem heare i install the d912pxy and archdps with the help of addon manager  but now when i make the new update the game crash on character load screen and close the game when i uninstal it all works erfect when i install again crash again .I try to remove riva tunner nothing , uninstal geforce experience and discord nothing close all overlays nothing . But 1 think remain the previous time i hade again the same isue then i format antire pc and dowload again gw2 the all third party softowares works fine . Im not sooure wheare is the preblem , i mean the probllem is in therd party softwares or in neww updates i think something trigered with updates but i dont know why if some one knows something please inform us

**Comment by Munzy** [comment] 2021-04-06 20:26
The newest release seems to be working.

**Comment by megai2** [comment] 2021-04-06 20:36
Should be working with released fixes

**Comment by gele05** [comment] 2021-04-06 20:57
It work with arcdps too?

**Comment by Munzy** [comment] 2021-04-06 20:58
> 
> 
> It work with arcdps too?

It worked for me while using arcdps.

**Comment by rodcampos21** [comment] 2021-04-06 21:13
Anyone stil crashing even with the new release??

**Comment by LinearBotSystems** [comment] 2021-04-06 21:27
Yupp for me it is still crashing after the update

**Comment by LinearBotSystems** [comment] 2021-04-06 21:41
Works every part of it ^^

**Comment by Jayshua83** [comment] 2021-04-06 23:04
We are still crashing with the latest update.

d912pxy 2.4.3.1
d3d9_wrapper
GW2 Radial 2.0
ReShade

**Comment by raven4444** [comment] 2021-04-07 06:24
It's still crashing, just after launch on characters screen.
[log.txt](https://github.com/megai2/d912pxy/files/6269395/log.txt)

**Comment by daflameone** [comment] 2021-04-07 07:20
Im having again crashes with the new update of dx12. Game just freezes when I launch it. It doesn't take me even to char log screen. Just a hand/cursor pops up and freeze. Need to restart my PC to can do things again.

Pls fix it :( like dx12 changes game experience for real :(

**Comment by daflameone** [comment] 2021-04-07 07:33
If I delete the .dll files in bin64 games works, BUT WITOUT THE dx12 AND IS INSANE SPIKES AND LAG :( pls need working dx12

**Comment by AEsylum** [comment] 2021-04-07 08:42
The fix stopped the crash but using Launch Buddy to launch multiple clients will fail. The launch buddy will indicate there are two clients running but you'll see only the first one. After about 5 min, a pop up will appear saying "Install cannot be completed. Please contact Support." Close that popup and Launch Buddy will stop indicating your 2nd client is running.

The first client is otherwise fine. I tried removing dx912 and kept arcDPS and can multi client successfully.

**Comment by Sagrime** [comment] 2021-04-09 00:36
I'm crashing when opening the map even with the last patch. I'm on a clean install of the game and tried with only dx12. The map make me crash 4 times out of 5. Reshade don't work anymore without dx12 (that's not a dx problem, I reinstalled reshade for dx9 after removing dx12, still don't work). So my game is actually ugly and I have FPS drops because I can't use Dx12. Hope this message can help u patching. Sorry for my English grammar, I'm still learning. Love you <3

**Comment by Ghostkat9** [comment] 2021-04-09 06:41
I'm not crashing but I am getting a weird error where it thinks my screenshots folder is full when it totally isn't.

**Comment by megai2** [comment] 2021-04-10 16:14
Added small change for shader length calculation, let me know if crashes is still here.
But please don't forget to attach d912pxy/log.txt

> 
> It's still crashing, just after launch on characters screen.
> [log.txt](https://github.com/megai2/d912pxy/files/6269395/log.txt)

log shows that you still have a old version in use, update to latest

quote from log
> 481BB1A4 [ info ] device | d912pxy version: v2.2 r554

**Comment by Sagrime** [comment] 2021-04-10 18:38
Hi. My game still crashing when I open the map window. Here's my Log file : 
[log.txt](https://github.com/megai2/d912pxy/files/6290541/log.txt)

**Comment by megai2** [comment] 2021-04-10 19:00
> 
> 
> Hi. My game still crashing when I open the map window. Here's my Log file :
> [log.txt](https://github.com/megai2/d912pxy/files/6290541/log.txt)

That is #335 disable depth detection or update ReShade

**Comment by Sagrime** [comment] 2021-04-10 19:54
Thank You. I removed reshade because i don't know how to disable depth detection. It works. I don't understand because my reshade is up to date and I'm using both dx12 and reshades since few years. First time I have this kind of problem. So my problem is temporarily solved. Thank u again.

**Comment by falconh** [comment] 2021-04-14 12:45
Hi,

My game is still crashing even with the latest release. Please find the log file.

[log.txt](https://github.com/megai2/d912pxy/files/6310853/log.txt)

**Comment by Ghostkat9** [comment] 2021-04-14 15:06
I think a big contributing factor to the crashes is the GW2Radial plugin. It hasn't been updated in forever and a half, so the current version is still in alpha. The guy who made it hasn't been responsive on Github to questions about it, either. Right now, there are graphical errors which occur whenever you use the hotkey to bring up the radial menu, evident both during load screens and if you're in a room with walls surrounding you, it'll create this white "ghosting" sort of effect on the geometry surrounding you. Since - at least on my end - it appears to be the trigger for a lot of the circumstances of the game crapping out, methinks the problem is on the GW2Radial end, and I don't know if/when that will be resolved with the maker of it being so unresponsive.

**Comment by megai2** [comment] 2021-04-14 16:56
> 
> 
> Hi,
> 
> My game is still crashing even with the latest release. Please find the log file.
> 
> [log.txt](https://github.com/megai2/d912pxy/files/6310853/log.txt)

Looks like heap corruption. 
Try disabling Discord overlay, Razer Cortex, DisplayFusion to avoid 3-rd party conflicts.



> 
> 
> I think a big contributing factor to the crashes is the GW2Radial plugin. It hasn't been updated in forever and a half, so the current version is still in alpha. The guy who made it hasn't been responsive on Github to questions about it, either. Right now, there are graphical errors which occur whenever you use the hotkey to bring up the radial menu, evident both during load screens and if you're in a room with walls surrounding you, it'll create this white "ghosting" sort of effect on the geometry surrounding you. Since - at least on my end - it appears to be the trigger for a lot of the circumstances of the game crapping out, methinks the problem is on the GW2Radial end, and I don't know if/when that will be resolved with the maker of it being so unresponsive.

GW2Radial alpha v2 should work just fine, only current non-alpha is problematic and 
it also should not create crash like problems. Only visual ones

**Comment by Ghostkat9** [comment] 2021-04-14 17:42
I would think any time anything bugs out, visual or otherwise, something under the hood is always a possible contributing factor to a crash. So when the visual bugs get very, very gnarly, especially on load screens, and it's always triggered by the input used to bring up the radial mount menu, I wouldn't necessarily rule that out as a culprit without giving it a look. And yes, this is with the current GW2Radial alpha that is out right now, not a previous version. When a game's recent update affects the way plugins behave, two plugins are known to have interactions with one another (e.g. the GW2 Radial bug fix note that says "Better d912pxy integration"), and only one of them (yours) has had any recent updates since said game update while the other one hasn't been updated since October of last year, and the input that triggers that plugin is what's causing the issues, I would certainly not rule out the possibility that the GW2Radial one might be in need of an update.

Never mind the fact that it has been in "alpha" since October 2020 with no news about when it's coming out of alpha, and Friendly0Fire hasn't responded to questions or issues about his plugin for months and has seemingly disappeared.

**Comment by falconh** [comment] 2021-04-15 08:50
> > Hi,
> > My game is still crashing even with the latest release. Please find the log file.
> > [log.txt](https://github.com/megai2/d912pxy/files/6310853/log.txt)
> 
> Looks like heap corruption.
> Try disabling Discord overlay, Razer Cortex, DisplayFusion to avoid 3-rd party conflicts.

Thanks. It worked.

It seems that the Discord Overlay does not work well with the system overlay from d912pxy. After disabling the system overlay from d912xy, the game works even with Discord Overlay being enabled.

**Comment by megai2** [comment] 2021-05-02 15:55
Original problem solved as it looks.

**Closed by megai2** 2021-05-02 15:55 UTC
Labels: crash
