### ISSUE TITLE
Arcdps crashing with D912pxy

### ISSUE THREAD

**Issue by Aphiola** [megai2/d912pxy#380] opened 2021-06-05 20:44 UTC
**Describe the bug**
d912pxy causes a Kernel Base crash with arcdps whenever you reach specific areas or parts of the storyline, it is fine everywhere else

**To Reproduce**

1. Run game
2. Head to mission Rending the Mantle (as an example, some other missions have issues but I can't remember)
3. Kill the waves of adds and in the bar stairs or the hallway, the game will crash

**Expected behavior**
Be able to play through the entire mission without issues

**Screenshots**
[arcdps_lastcrash.log](https://github.com/megai2/d912pxy/files/6603209/arcdps_lastcrash.log)

**Standard information**

1. Windows 10 update ver 21H1
2. Hardware info: cpu: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
			    ram: 9816MB / 16308MB used
			    gpu: NVIDIA GeForce GTX 1060 3GB
3. GPU Driver version 466.63
4. Version of d912pxy used Latest one from April 6, 2021

**Comment by MasterJam-ai** [comment] 2021-06-14 11:25
very similar issue here.
arcDPS and therefore GW2 crashing in basically 2 steps.
Fist step:
GW2 minimizes out of a sudden. 
After reopening it all arcDPS overlays are gone, but you can continue playing the game.
Second step:
Then, after while of gaming opening the map forces the game to crash.
It's always the map which is crashing the game, but only if arcDPS crashed before. 
It's not possible to crash the game by opening the map without step 1.

**Comment by megai2** [comment] 2021-06-22 07:21
Does not reproduces for me.

There is dxgi.dll present in log attached in first post. 
This means some stuff like ReShade are also in use. 

Please be aware that ReShade with enabled depth detection can bug out and crash.
Can't say for sure, but maybe newer ReShade have this problem fixed, try to update it and see if it helps.

**Comment by doryxbirb** [comment] 2021-07-15 09:08
> It's always the map

Not true. Mine crashed 3 times in the new Marionette event. First two looked casual, third time was entering the portal that move you on the platforms.

> There is dxgi.dll present in log attached in first post.

Removing arcDPS, d912pxy have no problems playing for hours in windowed fullscreen, without any other addon. So the problem is with arcDPS I suppose.

**Comment by doryxbirb** [comment] 2021-07-28 11:09
A little update after 13 days. I haven't had a single crash since last time I wrote here, same arcdps and d912pxy versions. After the initial wave of crashes, gw2 made several micro patches the following day. Maybe it was a GW2-side problem.

**Comment by megai2** [comment] 2021-07-31 09:54
Things are stabilized back to normal - i close the issue.

**Closed by megai2** 2021-07-31 09:54 UTC
Labels: 3rd party support, bug
