### ISSUE TITLE
Not actual fullscreen in fullscreen?

### ISSUE THREAD

**Issue by MeTTacuS** [megai2/d912pxy#262] opened 2020-06-20 09:03 UTC
Is the game not running in actual fullscreen mode when set to be running in fullscreen? The TacO overlay still works, and the gamma bar is ignored when set to fullscren mode, making me think that this is not true-fullscreen.

**Comment by Aussiemon** [comment] 2020-06-22 18:37
Sounds like you're using Fullscreen Optimizations:
[https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/](https://devblogs.microsoft.com/directx/demystifying-full-screen-optimizations/ )

**Comment by Squall-Leonhart** [comment] 2020-06-23 06:46
working as intended.

**Comment by megai2** [comment] 2020-06-23 13:40
@MeTTacuS as mentioned above looks like this is full screen optimizations that override true-fullscreen mode

you can try to disable them as said in linkned article

```
    Right Click on the Executable File (.exe) and Select Properties 
    Select the Compatibility Tab 
    Under Settings – Select “Disable Fullscreen Optimizations” 
    Click Apply  
```

**Comment by MeTTacuS** [comment] 2020-06-25 08:17
@megai2 Disabling fullscreen optimizations doens't seem to be having any effects. I was thinking that AMD settings might be interfering, but it does not seem like they're changing gw2 in any way (and before the addon fullscreen was working well)

I have made a few changes to the config.ini file, but none of them should be interfering with true-fullscreen. Any other ideas?

**Comment by megai2** [comment] 2020-06-25 09:41
> 
> 
> @megai2 Disabling fullscreen optimizations doens't seem to be having any effects. I was thinking that AMD settings might be interfering, but it does not seem like they're changing gw2 in any way (and before the addon fullscreen was working well)
> 
> I have made a few changes to the config.ini file, but none of them should be interfering with true-fullscreen. Any other ideas?

I'm simply routing full screen parameter to API, normally it works out from box, but sometimes underlying software like drivers, 3-rd party tools (reshade, rtss, etc) or said fullscreen optimizations can do whatever they want(like ignoring or modifing full screen parameter)

Tested it on my laptop and with disabled/enabled fullscreen optimizations it works like it should (gamma, alt-tab switching, etc).
win10 version is 18362

**Comment by MeTTacuS** [comment] 2020-06-25 09:49
I see. I can't think of anything that might be interfering, since I'm not using reshade or any other tuning 3rd party tools. I'll keep looking, if everything is fine on your side that means this most likely is something with my setup. I'll close this when I find a solution or after giving up on looking for it

**Comment by megai2** [comment] 2020-08-29 15:08
Well i close it for now, windows promotes no-exclusive fullscreen mode everywhere and d912pxy not works properly with exclusive fullscreen

**Closed by megai2** 2020-08-29 15:08 UTC
Labels: bug
