### ISSUE TITLE
Command line argument -mapLoadInfo overlay not rendered

### ISSUE THREAD

**Issue by Aussiemon** [megai2/d912pxy#266] opened 2020-06-27 17:22 UTC
**Log**
[log.txt](https://github.com/megai2/d912pxy/files/4840960/log.txt)

**Describe the bug**
The Dragon Bash game update added a new "mapLoadInfo" overlay at loading screens. D912pxy doesn't render this overlay. Using Windowed Fullscreen. Overlays disabled.

**To Reproduce**
1. [ Enable mapLoadInfo by adding -mapLoadInfo to your GW2 launch arguments](https://wiki.guildwars2.com/wiki/Command_line_arguments)
2.  Start the game
3.  Load a character

**Screenshots**
Without d912pxy:
![WithoutD912pxy](https://user-images.githubusercontent.com/13663574/85928072-88885600-b867-11ea-98a0-de550b467b82.jpg)

With d912pxy:
![WithD912pxy jpg](https://user-images.githubusercontent.com/13663574/85928073-8a521980-b867-11ea-849c-735b2aacbbb0.jpg)

**Standard information**
[DxDiag.txt](https://github.com/megai2/d912pxy/files/4840961/DxDiag.txt)
OS - Windows 10 Enterprise v1809
GPU - RTX 2080TI
CPU - i9-9900K CPU @ 3.60GHz
RAM - DDR4 32GB 3200
GPU Driver version: NVIDIA 442.59
Version of d912pxy used: 2.1.2

**Comment by Aussiemon** [comment] 2020-06-27 17:25
Old mapLoadInfo for comparison:
![OldMapLoadInfo](https://user-images.githubusercontent.com/13663574/85928270-f6814d00-b868-11ea-9ae4-c3fc369e5b46.jpg)

**Comment by IsmetBesic** [comment] 2020-06-27 19:36
Duplicate of #264. 

The issue has already been fixed in one of the intermediates commits. You can download a more up-to-date build by following one of the AppVeyor links next to the commits or waiting until @megai2 promotes a build to full release (likely 2.2).

**Closed** 2020-06-28 06:14 UTC
Labels: bug
